language: node_js
sudo: false
node_js: 6
services: postgresql
install: npm install
env:
  global:
    - NODE_ENV=travis
script: npm run travis
notifications:
  slack: kutyba:VqcGRPxdmhrkALzIfbwzY50e
  email: false
