version: '2'

services:
  node:
    image: node:6
    ports:
      - 3000:3000
    volumes:
      - .:/app
    links:
      - postgres
      - postgres-test
    working_dir: /app
    command: npm start

  postgres:
    image: postgres:9
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 9deh7fsg879h

  postgres-test:
    image: postgres:9
    volumes:
      - ./data/postgres-test:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 9deh7fsg879h
